
workflows:
  sleep-workflow:
    name: Sleep Forever
    max_build_duration: 120 # Max is 120 minutes (2 hours) on free plan
    scripts:
      - name: Sleep forever
        script: |
          echo "Starting sleep..."
          sleep infinity
